# Details of a user
---
name: Test User
phone: 0786984644
email: testuser@emag.ro
age: 30
partnumber: MOMOF5
address:
  line1: My Address Line 1
  line2: Address line 2
  city: Washington D.C.
  zip: 20000
roles:
  - User
  - Edit